concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner"
  url = "http://e22236c0f4fe/"
  id = 1
  token = "xRdSozrGzaBYEmys2bgq"
  token_obtained_at = 2023-11-28T12:21:36Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "first"
  url = "http://e22236c0f4fe/"
  id = 1
  token = "e_87NA73zv-F6_2JQyb9"
  token_obtained_at = 2023-12-05T20:59:18Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  [runners.cache]
    MaxUploadedArchiveSize = 0
