stages:
  - build
  - test
  - check

check:
  stage: check
  dependencies:
    - test
  script:
    - 

build:
  stage: build
  dependencies:
    - check
  script:
    - dotnet build --configuration Release
    - dotnet publish --no-build --no-restore --configuration Release --output $CI_PROJECT_DIR/publish/

test:
  stage: test
  script:
    - echo "Running test job"
