stages:
  - test
  - build
  - release

build:
  stage: build
  before_script:
    - 'dotnet restore'
  needs:
    - test
  script:
    - dotnet build

test:
  stage: test
  script:
    - dotnet test

release:
  stage: release
  needs:
    - build
  before_script:
    - 'dotnet restore'
  script:
    - dotnet build -c Release
    - dotnet publish -c Release -o $CI_PROJECT_DIR/publish/ ./WebApILinux.csproj