version: '3'

services:
  api:
    restart: always
    build: ./api
    ports:
      - 5555:5050
    depends_on:
      - mysql
  frontend:
    restart: always
    build: ./frontend
    ports:
      - 8954:9090
  mysql:
    restart: always
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=time_db
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    restart: always
    image: adminer
    ports:
      - 8888:8080

volumes:
  mysql_data: